server:
  port: 8889
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        loans-out:
          destination: loans
          contentType: application/json

