server:
  port: 8887
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        loans-in:
          destination: loans
          contentType: application/json

